import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/ui/Menu";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="font-roboto bg-[#efefef] flex justify-center">
        <div className="justify-between flex flex-col w-full max-w-screen-2xl min-h-screen">
          <Menu />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
