import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/ui/Menu";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className=" bg-[#efefef] flex justify-center">
        <div className="justify-between flex flex-col w-full max-w-screen-2xl min-h-screen">
          <Menu />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
